[package]
name = "thetrashman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../../lib" }
glam = "0.22.0"
log = "0.4.17"
rayon = "1.6.0"
rand = "0.8.5"
ordered-float = "3.4.0"